common:
  fp16: false
  log_format: json
  log_interval: 10
  # wandb_project: 3kg-pretraining

checkpoint:
  save_dir: checkpoints
  save_interval: 1
  keep_last_epochs: 1
  save_interval_updates: 0
  no_epoch_checkpoints: false

task:
  _name: ecg_pretraining
  data: ???
  normalize: false
  enable_padding: true
  inferred_3kg_config:
    angle: 45
    scale: 1.5
    mask_ratio: 0.5

dataset:
  num_workers: 6
  max_tokens: null
  batch_size: 64
  valid_subset: ""
  disable_validation: true

distributed_training:
  distributed_world_size: 8

criterion:
  _name: 3kg

optimization:
  max_epoch: 200
  lr: [5e-5]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: fixed
  warmup_updates: 0

model:
  _name: 3kg
  apply_mask: false
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  encoder_embed_dim: 768
  in_d: 12